# Generated by Django 4.2.30 on 2026-05-11 16:48
import json
import logging
import os
import sys

from django.conf import settings
from django.db import migrations, models

# Get an instance of a logger
logger = logging.getLogger(__name__)

def check_json(apps, schema_editor):
    file_path = os.path.join(settings.BASE_DIR, 'data', 'playgrounds.json')
    if not os.path.isfile(file_path):
        logger.critical("[ERROR] missed playgrounds.json")
        sys.exit(1)


def create_first_data(apps, schema_editor):
    # Use apps.get_model to get the historical version of your model
    PlaygroundModel = apps.get_model('rentplayground', 'Playground')

    file_path = os.path.join(settings.BASE_DIR, 'data', 'playgrounds.json')
    if not os.path.isfile(file_path):
        logger.critical("[ERROR] missed playgrounds.json")
        sys.exit(1)

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for playgroundId in data['playgrounds']:
        playgroundData = data['playgrounds'][playgroundId]
        PlaygroundModel.objects.get_or_create(
            id=playgroundId,
            name=playgroundData.get('name'),
            type=playgroundData.get('type'),
            price=playgroundData.get('price'),
            images=playgroundData.get('images')
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(check_json, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='error', max_length=20)),
                ('type', models.CharField(default='error', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('images', models.CharField(default='error', max_length=20)),
            ],
        ),
        migrations.RunPython(create_first_data),
    ]
